dataset:
  root: '/root/storage/dataset/kspon'
  clean: 'data/Ksponspeech/eval_clean.trn'
  noise: 'data/Ksponspeech/eval_other.trn'

setting:
  model_type: 'segan'
  opt_type: 'noam'
  loss_type: 'mse'
  device: 'cuda'

se_model:
  #out_channel: ???
  #in_channel: 2
  #kernel_size: 31
  #stride : 2
  dis_n_layers: 11
  gen_n_layers: 11

optimizer:
  d_model: 512
  warmup: 45000
  factor: 1

train:
  device: 'cuda'
  batch_size: 8
  epochs: 50
  save_epoch: 1
  
feature:
  spec: 
    sample_rate: 16000
    n_mels: 80
    #n_fft: 512
    #hop_length: 256
    #win_length: 512
    win_length: 0.025
    win_stride: 0.01
    normalized: False
  augment:
    spec_augment: 0.5
    time_shifting: 0
    noise_injecting: 0
  